### ISSUE TITLE
Edit and Delete buttons stop working on page change

### ISSUE THREAD

**Issue by vesmor** [vesmor/ContactManager#86]
This is a bug I introduced sorry about that
When clicking on a contact, clicking the "Edit" button, then the "Cancel" button to discard changes, it'll bring you back to the non-editing Contact details page but when it does, none of the buttons on the contact card details work, until you click away and then back on that card.
I suspect it's because during the Cancel (Discard Changes) click event, I set the "contactDetailsElement.innerHTML" to a copy and paste of the Contact Details Non-editable page.

**Comment by shinobi-404** [comment]
Currently Fixed
